Задание 1
apply()

In [ ]:
import pandas as pd
# create a series
s = pd.Series([1, 2, 3])
# apply a function to each element in the series
s = s.apply(lambda x: x * 2)
print(s)

0    2
1    4
2    6
dtype: int64

In [ ]:
import pandas as pd

# Создаем DataFrame с названиями фруктов
df = pd.DataFrame({'fruits': ['apple', 'banana', 'cherry', 'date']})

# Применяем функцию apply для преобразования в верхний регистр
df['fruits_upper'] = df['fruits'].apply(lambda x: x.upper())

print(df)

   fruits fruits_upper
0   apple        APPLE
1  banana       BANANA
2  cherry       CHERRY
3    date         DATE

transform

In [ ]:
import pandas as pd
s = pd.Series([1, 2, 3])
def add_one(x):
    return x + 1
s.apply(add_one)

0    2
1    3
2    4
dtype: int64

In [ ]:
import pandas as pd

# Создаем DataFrame с данными о продажах
df = pd.DataFrame({'store': ['A', 'A', 'B', 'B'],
                   'sales': [100, 200, 150, 250]})

# Нормализуем продажи по каждому магазину
df['normalized_sales'] = df.groupby('store')['sales'].transform(lambda x: (x - x.mean()) / x.std())

print(df)

  store  sales  normalized_sales
0     A    100         -0.707107
1     A    200          0.707107
2     B    150         -0.707107
3     B    250          0.707107

drop()

In [ ]:
import pandas as pd
# создадим фрейм данных
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
# отбросим колонку 'B'
df = df.drop(columns=['B'])
print(df)

   A
0  1
1  2

In [ ]:
import pandas as pd

# Создаем DataFrame с данными
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})

# Удаляем столбец 'B'
df_dropped = df.drop(columns=['B'])

print(df_dropped)

   A  C
0  1  7
1  2  8
2  3  9

drop_duplicates()

In [ ]:
import pandas as pd
# создадим серию с дублирующимися значениями
s = pd.Series([1, 2, 2])
# удалим дубликаты
s = s.drop_duplicates()
print(s)

0    1
1    2
dtype: int64

In [ ]:
import pandas as pd

# Создаем DataFrame с дубликатами
df = pd.DataFrame({'A': [1, 1, 2, 3],
                   'B': [4, 4, 5, 6]})

# Удаляем дубликаты по столбцу 'A'
df_unique = df.drop_duplicates(subset=['A'])

print(df_unique)

   A  B
0  1  4
2  2  5
3  3  6

Задание 2
pandas.Series.sum
Series.sum(axis=None, skipna=True, numeric_only=False, min_count=0, **kwargs)

In [14]:
import pandas as pd
#Пример с сайта
idx = pd.MultiIndex.from_arrays([
    ['warm', 'warm', 'cold', 'cold'],
    ['dog', 'falcon', 'fish', 'spider']],
    names=['blooded', 'animal'])

s = pd.Series([4, 2, 0, 8], name='legs', index=idx)

s.sum()

14

In [15]:
import pandas as pd

import pandas as pd

sales = pd.Series([100, 200, 150, 300])

total_sales = sales.sum()
total_sales

750

Задание 3

In [ ]:
import pandas as pd

N = int(input("Введите количество чисел: "))
numbers = [float(input()) for _ in range(N)]

series = pd.Series(numbers)

mean_value = series.mean()

result = series / mean_value

print("Ответ:")
print(result)

Введите количество чисел: 3
1
2
3
Ответ:
0    0.5
1    1.0
2    1.5
dtype: float64